name: douyin without watermarker analysis
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest



    steps:
      # 发布Release
      - name: Create Release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      #上传构建结果到Release
      - name: Upload Release Resources
        id: upload_release_resources
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          release_name: ./release.tgz
          asset_name: release.tgz
          asset_content_type: application/x-tgz

      #部署到服务器
      - name: Deploy to My Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script:
            cd /data/soft
            wget https://github.com/STZZ-1992/douyin_analysis/releases/latest/download/release.tgz -o release.tgz
            tar -zxvf release.tgz
            conda activate stzzWang
            ll

